library sharifngo.globals;
String token;
int tokenExpireTime;
int userId;
int madadkarId;
int madadkarCode;
String madadkarFname;
String madadkarLname;
String serverUrl='http://soft.sharifngo.com:8020';